# Dockerfile for production
FROM node:16 as builder

# Create and set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code (except for what is in .dockerignore)
COPY . .

# Build the application
RUN npm run build

# Production stage
FROM node:16-alpine

# Create and set working directory
WORKDIR /app

# Copy only the necessary files from the builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# Set environment variable
ENV NODE_ENV=production

# Expose the port for the production server
EXPOSE 5173

# Command to run the application in production mode
CMD ["npm", "run", "start"]
