version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./compose/local/.env.local:/app/.env.local
    environment:
      - NODE_ENV=development
    command: npm run dev
